# Generated by Django 3.0.7 on 2020-06-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='conferir2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='conferir3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='conferir4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='conferir5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
    ]
