# Generated by Django 3.0.7 on 2020-06-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200619_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='pule',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
