# Generated by Django 3.0.7 on 2020-07-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_avaliacao_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao_teste',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
