# Generated by Django 3.0.7 on 2020-07-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_online_esta'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
